### PR TITLE
Upgrade bash to 5.0.7

### PR DESCRIPTION
**Pull request by chrisgilmerproj**
Also:
- Enforce Debian Stretch (CircleCI allows the suffix `-jesse` or `-stretch` and it's not clear which one you get unless you specify. Also is better documentation about what we're using.)
- Silent curl commands (This extra output I didn't find useful)

Enforces a version of bash by using the latest that comes with Homebrew.  This means our bash scripts can be relied on to work the same in CircleCI as well as locally in the same way.

Using this for https://github.com/transcom/mymove/pull/1721

Bash References:
- https://ftp.gnu.org/gnu/bash/
- https://formulae.brew.sh/formula/bash
- https://github.com/Homebrew/homebrew-core/blob/master/Formula/bash.rb
- https://www.gnu.org/software/bash/manual/bash.pdf
- https://www.stevejenkins.com/blog/2014/09/how-to-manually-update-bash-to-patch-shellshock-bug-on-older-fedora-based-systems/

CircleCI References:
- https://circleci.com/docs/2.0/circleci-images/#best-practices

### CODE REVIEW

**Comment by chrisgilmerproj** [comment]
Btw, current version on those containers is `4.4.12(1)-release` and the new one will be `5.0.2(1)-release`.

**Comment by brainsik** [comment]
Oof. I have mixed feelings about this. My main worry is that BASH is a pretty core, system level package. I'm very uncomfortable mucking about with it, even if it _is_ in `/usr/local`.

Curious to hear other opinions while I chew on it.

@chrisgilmerproj Can you give a use case for this? Is there a BASH 5 feature the team is hoping to use?

**Review by brainsik — CHANGES_REQUESTED** [review]
Please also add `-S` when using `-s` with `curl`.

**Comment by chrisgilmerproj** [comment]
@brainsik - The main thing I want to accomplish here is ensuring that what developers are using locally while they develop is what is being run by CircleCI remotely.  This means a deploy script run by a user should have the exact same outcome as run in CircleCI with no ambiguity.

Honestly there are no features that 4.4 doesn't have that I need in 5.0. But trying to install 4.4 on my Mac is a lot more difficult than just staying up to date with `brew install bash`.  Not to mention it wouldn't just be me trying to install 4.4 but everyone on my project.  Also, using the https://github.com/ueokande/bashvm project feels pretty heavy.

This doesn't block me and I also have similar reservations. But if I can put guardrails around one more thing that turns out to matter in development then I'm happy to add it.

**Comment by chrisgilmerproj** [comment]
> Please also add `-S` when using `-s` with `curl`.

Added:) bd177e4

**Comment by chrisgilmerproj** [comment]
@brainsik - any more thoughts on this one?

**Comment by brainsik** [comment]
I was hoping others would chime in. :-) Okay, some additional thoughts:

1. Is this solving a real problem you've run into? or is it trying to avoid a future problem?
1. How will you stay on top of security releases? Similar to what we do for the other packages and just manually watch for `brew` updates?
1.  How about start this out as a separately tagged image (similar to what I did for Packer) and you can test it out with the MilMove project? If that goes fine, then we could bring it into base.

**Comment by chrisgilmerproj** [comment]
Let's see if I can answer:

1. Trying to avoid a future problem.  We seem to version everything for this same reason, it's not just features but attempting to avoid finding out a mis-matched version caused us pain.

2. I was going to rely on brew updates.  Enough people on MilMove update brew regularly that along with our script that checks the bash version we should catch this pretty immediately.  And then we'll just update the package.

3. I considered having this as a separate image but that gets me going down a long chain of asking why we don't manage this in the MilMove project directly instead of in this shared repo.

**Comment by chrisgilmerproj** [comment]
@brainsik - I'd love to get this in but its not a blocker to me. So instead of leaving it open I'd rather merge or close it.  And if we close then at least we have a record of how to address this if its a bigger issue in the future.

**Pull request closed without merging**
