### PR TITLE
pin yarn

### PR DESCRIPTION
**Pull request by pjdufour-truss**
Pin yarn to `1.10.1-1` to manage upgrades

### CODE REVIEW

**Review by dynamike — APPROVED** [review]
LGTM. @tinyels, I also added you to this PR to make sure this looks okay. This repo is the image that the MyMove CircleCI builds use.

**Comment by tinyels** [comment]
I'm not sure we need to do this. We haven't asked engineers to pin since this is the first time we have had a yarn issue. And even this issue didn't break the system for people using older version of yarn.

**Comment by pjdufour-truss** [comment]
@tinyels the mismatched versions of yarn prevent the more aggressive caching that we're trying to do in CircelCI with the goal of running downloading/installing dependencies just once, since we need to key on the sha256sum of the lock file.  Currently, when mismatched versions lead to different checksums for the lock file, which leads to cache misses.

Yes, this might be something that doesn't hit us again for a while but I'd rather make this dependency explicit rather than implicit (dependent on when this container was built).

**Comment by pjdufour-truss** [comment]
Since the version of yarn breaking our workflow is rare, it seems our app teams would rather upgrade when CI fails rather than pinning on an out of date version.

**Pull request closed without merging**
