### PR TITLE
Remove dep from the image

### PR DESCRIPTION
**Pull request by chrisgilmerproj**
When we merge https://github.com/transcom/mymove/pull/1932 then MilMove won't need `dep` any longer! I'm not aware of any other packages needing this so it's worth removing.

### CODE REVIEW

**Comment by kilbergr** [comment]
I don't want to approve until the other one is landed. Otherwise, LGTM.
Also this is in "draft state"--idk what that means but it says it can't be merged yet.

**Comment by chrisgilmerproj** [comment]
> I don't want to approve until the other one is landed. Otherwise, LGTM.
> Also this is in "draft state"--idk what that means but it says it can't be merged yet.

Agreed, I just wanted this on deck for when the other PR is approved.  

Also, `draft state` is a new Github feature! https://github.blog/2019-02-14-introducing-draft-pull-requests/

**Review by kahlouie — APPROVED** [review]
The dependency has been merged! :shipit:

**Comment by brainsik** [comment]
I'll update the README.

**Comment by chrisgilmerproj** [comment]
> I'll update the README.

Thanks!

**Pull request merged**
